=== fmarkulin/fer-or/schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://github.com/fmarkulin/blob/main/schema.json",
  "type": "array",
  "default": [],
  "title": "The Books and their authors Schema",
  "description": "A list of books and their authors",
  "items": {
    "type": "object",
    "title": "A Books and their authors properties Schema",
    "required": [
      "number_of_pages",
      "title",
      "publish_date",
      "publishers",
      "last_modified",
      "type",
      "revision",
      "latest_revision",
      "authors",
      "key",
      "subjects"
    ],
    "properties": {
      "number_of_pages": {
        "type": "integer",
        "title": "The number_of_pages Schema",
        "description": "Number of pages in the book",
        "examples": [127, 78, 192, 26, 200, 48, 298, 331, 96]
      },
      "title": {
        "type": "string",
        "title": "The title Schema",
        "description": "The title of the book",
        "examples": [
          "Brodie's Notes on Emily Bronte's \"Wuthering Heights\" (Brodies Notes)",
          "Aristophanes, ein Spiegel unserer Zeit.",
          "War in Europe",
          "VCRs \u0026 camcorders for dummies"
        ]
      },
      "publish_date": {
        "type": "string",
        "title": "The publish_date Schema",
        "description": "The date the book was published",
        "examples": ["August 7, 1992", "1913"]
      },
      "publishers": {
        "type": "array",
        "title": "The publishers Schema",
        "description": "The publishers of the book",
        "items": {
          "type": "string",
          "title": "A publisher Schema",
          "examples": ["Palgrave Macmillan", "P. Schettlers", "Presidio"]
        },
        "examples": [
          ["Palgrave Macmillan"],
          ["P. Schettlers"],
          ["Presidio"],
          ["Palgrave Macmillan", "Presidio"]
        ]
      },
      "last_modified": {
        "type": "string",
        "title": "The last_modified Schema",
        "description": "The timestamp the book was last modified",
        "examples": ["2022-11-15T20:13:03.789779", "2022-12-17T03:01:10.857196"]
      },
      "type": {
        "type": "string",
        "title": "The type Schema",
        "description": "The type of the book",
        "examples": ["edition"]
      },
      "revision": {
        "type": "integer",
        "title": "The revision Schema",
        "description": "The revision of the book",
        "examples": [13, 3, 10, 5, 2, 6]
      },
      "latest_revision": {
        "type": "integer",
        "title": "The latest_revision Schema",
        "description": "The latest revision of the book",
        "examples": [13, 3, 10, 5, 2, 6]
      },
      "authors": {
        "type": "array",
        "title": "The authors Schema",
        "description": "The authors of the book",
        "items": {
          "type": "object",
          "title": "A author Schema",
          "description": "A author of the book",
          "required": ["last_modified", "type", "name", "key", "revision"],
          "properties": {
            "last_modified": {
              "type": "string",
              "title": "The last_modified Schema",
              "examples": [
                "2008-08-30 03:01:23.375753",
                "2008-04-29 15:03:11.581851"
              ]
            },
            "type": {
              "type": "string",
              "title": "The type Schema",
              "description": "The type of the entry",
              "examples": ["author"]
            },
            "name": {
              "type": "string",
              "title": "The name Schema",
              "description": "The name of the author",
              "examples": [
                "Norman T. Carrington",
                "A. B Kneisel",
                "Sidney C. Moody",
                "W. E. Hamilton",
                "Walker, John",
                "L. N. Carrier",
                "Rose, A.",
                "Gordon McComb",
                "Marie Jones",
                "Lorna Read"
              ]
            },
            "key": {
              "type": "string",
              "title": "The key Schema",
              "description": "The key of the author",
              "examples": [
                "OL1158982A",
                "OL4473583A",
                "OL581008A",
                "OL5295787A",
                "OL2555401A",
                "OL5288239A",
                "OL2153880A",
                "OL51749A",
                "OL500580A",
                "OL2802829A"
              ]
            },
            "revision": {
              "type": "integer",
              "title": "The revision Schema",
              "description": "The revision of the author",
              "examples": [2, 1]
            }
          },
          "examples": [
            {
              "last_modified": "2008-08-19 18:21:52.259027",
              "type": "author",
              "name": "Norman T. Carrington",
              "key": "OL1158982A",
              "revision": 2
            },
            {
              "type": "author",
              "name": "A. B Kneisel",
              "last_modified": "2008-09-02 18:39:32.675717",
              "revision": 1,
              "key": "OL4473583A"
            }
          ]
        },
        "examples": [
          [
            {
              "last_modified": "2008-08-19 18:21:52.259027",
              "type": "author",
              "name": "Norman T. Carrington",
              "key": "OL1158982A",
              "revision": 2
            }
          ],
          [
            {
              "type": "author",
              "name": "A. B Kneisel",
              "last_modified": "2008-09-02 18:39:32.675717",
              "revision": 1,
              "key": "OL4473583A"
            }
          ]
        ]
      },
      "key": {
        "type": "string",
        "title": "The key Schema",
        "description": "The key of the book",
        "examples": ["OL10551435M", "OL13994901M"]
      },
      "subjects": {
        "type": "array",
        "title": "The subjects Schema",
        "description": "The subjects of the book",
        "items": {
          "type": "string",
          "title": "A subject Schema",
          "examples": [
            "English literature: literary criticism",
            "Novels, other prose \u0026 writers: 19th century",
            "English",
            "World War, 1939-1945 -- Campaigns -- Europe."
          ]
        },
        "examples": [
          [
            "English literature: literary criticism",
            "Novels, other prose \u0026 writers: 19th century",
            "Designed / suitable for A \u0026 AS Level",
            "For National Curriculum Key Stage 4 \u0026 GCSE",
            "Study guides, home study \u0026 revision notes",
            "English",
            "Children: Young Adult (Gr. 7-9)"
          ],
          ["Aristophanes"],
          [
            "World War, 1939-1945 -- Campaigns -- Europe.",
            "World War, 1939-1945 -- Campaigns -- Europe -- Pictorial works."
          ]
        ]
      }
    },
    "examples": [
      {
        "number_of_pages": 127,
        "title": "Brodie's Notes on Emily Bronte's \"Wuthering Heights\" (Brodies Notes)",
        "publish_date": "August 7, 1992",
        "publishers": ["Palgrave Macmillan"],
        "last_modified": "2022-11-15T20:13:03.789779",
        "type": "edition",
        "revision": 13,
        "latest_revision": 13,
        "authors": [
          {
            "last_modified": "2008-08-19 18:21:52.259027",
            "type": "author",
            "name": "Norman T. Carrington",
            "key": "OL1158982A",
            "revision": 2
          }
        ],
        "key": "OL10551435M",
        "subjects": [
          "English literature: literary criticism",
          "Novels, other prose \u0026 writers: 19th century",
          "Designed / suitable for A \u0026 AS Level",
          "For National Curriculum Key Stage 4 \u0026 GCSE",
          "Study guides, home study \u0026 revision notes",
          "English",
          "Children: Young Adult (Gr. 7-9)"
        ]
      },
      {
        "revision": 3,
        "publishers": ["P. Schettlers"],
        "key": "OL13994901M",
        "number_of_pages": 78,
        "type": "edition",
        "latest_revision": 3,
        "title": "Aristophanes, ein Spiegel unserer Zeit.",
        "subjects": ["Aristophanes"],
        "authors": [
          {
            "type": "author",
            "name": "A. B Kneisel",
            "last_modified": "2008-09-02 18:39:32.675717",
            "revision": 1,
            "key": "OL4473583A"
          }
        ],
        "publish_date": "1913",
        "last_modified": "2010-04-13T09:56:10.635564"
      },
      {
        "revision": 10,
        "type": "edition",
        "key": "OL1413776M",
        "publish_date": "1993",
        "authors": [
          {
            "type": "author",
            "name": "Sidney C. Moody",
            "last_modified": "2008-08-30 03:01:23.375753",
            "key": "OL581008A",
            "revision": 2
          }
        ],
        "publishers": ["Presidio"],
        "title": "War in Europe",
        "number_of_pages": 192,
        "last_modified": "2022-12-05T06:01:35.024861",
        "subjects": [
          "World War, 1939-1945 -- Campaigns -- Europe.",
          "World War, 1939-1945 -- Campaigns -- Europe -- Pictorial works."
        ],
        "latest_revision": 10
      }
    ]
  },
  "examples": [
    [
      {
        "number_of_pages": 127,
        "title": "Brodie's Notes on Emily Bronte's \"Wuthering Heights\" (Brodies Notes)",
        "publish_date": "August 7, 1992",
        "publishers": ["Palgrave Macmillan"],
        "last_modified": "2022-11-15T20:13:03.789779",
        "type": "edition",
        "revision": 13,
        "latest_revision": 13,
        "authors": [
          {
            "last_modified": "2008-08-19 18:21:52.259027",
            "type": "author",
            "name": "Norman T. Carrington",
            "key": "OL1158982A",
            "revision": 2
          }
        ],
        "key": "OL10551435M",
        "subjects": [
          "English literature: literary criticism",
          "Novels, other prose \u0026 writers: 19th century",
          "Designed / suitable for A \u0026 AS Level",
          "For National Curriculum Key Stage 4 \u0026 GCSE",
          "Study guides, home study \u0026 revision notes",
          "English",
          "Children: Young Adult (Gr. 7-9)"
        ]
      },
      {
        "revision": 3,
        "publishers": ["P. Schettlers"],
        "key": "OL13994901M",
        "number_of_pages": 78,
        "type": "edition",
        "latest_revision": 3,
        "title": "Aristophanes, ein Spiegel unserer Zeit.",
        "subjects": ["Aristophanes"],
        "authors": [
          {
            "type": "author",
            "name": "A. B Kneisel",
            "last_modified": "2008-09-02 18:39:32.675717",
            "revision": 1,
            "key": "OL4473583A"
          }
        ],
        "publish_date": "1913",
        "last_modified": "2010-04-13T09:56:10.635564"
      },
      {
        "revision": 10,
        "type": "edition",
        "key": "OL1413776M",
        "publish_date": "1993",
        "authors": [
          {
            "type": "author",
            "name": "Sidney C. Moody",
            "last_modified": "2008-08-30 03:01:23.375753",
            "key": "OL581008A",
            "revision": 2
          }
        ],
        "publishers": ["Presidio"],
        "title": "War in Europe",
        "number_of_pages": 192,
        "last_modified": "2022-12-05T06:01:35.024861",
        "subjects": [
          "World War, 1939-1945 -- Campaigns -- Europe.",
          "World War, 1939-1945 -- Campaigns -- Europe -- Pictorial works."
        ],
        "latest_revision": 10
      }
    ]
  ]
}

=== fmarkulin/fer-or/public/books.json
[
  {
    "number_of_pages": 127,
    "title": "Brodie's Notes on Emily Bronte's \"Wuthering Heights\" (Brodies Notes)",
    "publish_date": "August 7, 1992",
    "publishers": [
      "Palgrave Macmillan"
    ],
    "last_modified": "2022-11-15T20:13:03.789779",
    "type": "edition",
    "revision": 13,
    "latest_revision": 13,
    "authors": [
      {
        "last_modified": "2008-08-19 18:21:52.259027",
        "type": "author",
        "name": "Norman T. Carrington",
        "key": "OL1158982A",
        "revision": 2
      }
    ],
    "key": "OL10551435M",
    "subjects": [
      "English literature: literary criticism",
      "Novels, other prose & writers: 19th century",
      "Designed / suitable for A & AS Level",
      "For National Curriculum Key Stage 4 & GCSE",
      "Study guides, home study & revision notes",
      "English",
      "Children: Young Adult (Gr. 7-9)"
    ]
  },
  {
    "revision": 3,
    "publishers": [
      "P. Schettlers"
    ],
    "key": "OL13994901M",
    "number_of_pages": 78,
    "type": "edition",
    "latest_revision": 3,
    "title": "Aristophanes, ein Spiegel unserer Zeit.",
    "subjects": [
      "Aristophanes"
    ],
    "authors": [
      {
        "type": "author",
        "name": "A. B Kneisel",
        "last_modified": "2008-09-02 18:39:32.675717",
        "revision": 1,
        "key": "OL4473583A"
      }
    ],
    "publish_date": "1913",
    "last_modified": "2010-04-13T09:56:10.635564"
  },
  {
    "revision": 10,
    "type": "edition",
    "key": "OL1413776M",
    "publish_date": "1993",
    "authors": [
      {
        "type": "author",
        "name": "Sidney C. Moody",
        "last_modified": "2008-08-30 03:01:23.375753",
        "key": "OL581008A",
        "revision": 2
      }
    ],
    "publishers": [
      "Presidio"
    ],
    "title": "War in Europe",
    "number_of_pages": 192,
    "last_modified": "2022-12-05T06:01:35.024861",
    "subjects": [
      "World War, 1939-1945 -- Campaigns -- Europe.",
      "World War, 1939-1945 -- Campaigns -- Europe -- Pictorial works."
    ],
    "latest_revision": 10
  },
  {
    "key": "OL21357082M",
    "title": "Muskoka sketch",
    "revision": 5,
    "latest_revision": 5,
    "authors": [
      {
        "type": "author",
        "name": "W. E. Hamilton",
        "last_modified": "2008-09-28 21:35:54.283711",
        "revision": 1,
        "key": "OL5295787A"
      }
    ],
    "subjects": [
      "Muskoka (Ont. : District) -- Description and travel.",
      "Muskoka (Ont. : District) -- History."
    ],
    "publishers": [
      "Times Printing Company"
    ],
    "type": "edition",
    "publish_date": "1983",
    "number_of_pages": 26,
    "last_modified": "2012-08-08T21:10:59.924864"
  },
  {
    "last_modified": "2012-08-07T10:18:24.946860",
    "latest_revision": 3,
    "number_of_pages": 200,
    "revision": 3,
    "title": "A Letter to Alexander Knox, Esq. M.R.I.A.",
    "key": "OL22885087M",
    "publishers": [
      "Printed by H. Colbert"
    ],
    "publish_date": "1803",
    "authors": [
      {
        "name": "Walker, John",
        "revision": 2,
        "type": "author",
        "key": "OL2555401A",
        "last_modified": "2012-06-07T08:18:43.478466"
      }
    ],
    "type": "edition",
    "subjects": [
      "Methodists -- Ireland."
    ]
  },
  {
    "publishers": [
      "L.J. Demers"
    ],
    "last_modified": "2020-05-21T10:17:30.189173",
    "number_of_pages": 48,
    "type": "edition",
    "subjects": [
      "Credit",
      "Banks and banking"
    ],
    "title": "Les Institutions de credit-foncier. Quelques notes sur leur but, leur organisation et leur origine",
    "latest_revision": 2,
    "authors": [
      {
        "type": "author",
        "last_modified": "2008-09-28 19:19:44.680177",
        "revision": 1,
        "name": "L. N. Carrier",
        "key": "OL5288239A"
      }
    ],
    "publish_date": "1880",
    "revision": 2,
    "key": "OL25465456M"
  },
  {
    "publish_date": "1965",
    "revision": 3,
    "last_modified": "2020-05-15T03:58:15.877548",
    "number_of_pages": 298,
    "title": "Psaumes et prière chrétienne",
    "key": "OL26545029M",
    "subjects": [
      "Criticism, interpretation",
      "Bible"
    ],
    "type": "edition",
    "authors": [
      {
        "last_modified": "2008-04-01 03:28:50.625462",
        "type": "author",
        "name": "Rose, A.",
        "revision": 1,
        "key": "OL2153880A"
      }
    ],
    "latest_revision": 3,
    "publishers": [
      "Biblica, Publications de Saint André"
    ]
  },
  {
    "publishers": [
      "IDG Books Worldwide"
    ],
    "type": "edition",
    "title": "VCRs & camcorders for dummies",
    "revision": 10,
    "subjects": [
      "Home video systems.",
      "Video tape recorders.",
      "Camcorders.",
      "Television -- Equipment and supplies."
    ],
    "number_of_pages": 331,
    "key": "OL824543M",
    "publish_date": "1995",
    "last_modified": "2020-11-20T15:58:35.964496",
    "authors": [
      {
        "name": "Gordon McComb",
        "last_modified": "2008-09-12 15:59:54.226722",
        "key": "OL51749A",
        "type": "author",
        "revision": 2
      }
    ],
    "latest_revision": 10
  },
  {
    "subjects": [
      "Protestants -- Northern Ireland -- Belfast -- Drama.",
      "Soccer -- Northern Ireland -- Belfast -- Drama."
    ],
    "revision": 6,
    "publish_date": "1995",
    "latest_revision": 6,
    "publishers": [
      "New Island Books",
      "Nick Hern Books"
    ],
    "key": "OL904472M",
    "last_modified": "2020-11-21T08:24:06.596410",
    "authors": [
      {
        "type": "author",
        "last_modified": "2008-08-31 21:11:02.340397",
        "name": "Marie Jones",
        "revision": 2,
        "key": "OL500580A"
      }
    ],
    "number_of_pages": 48,
    "type": "edition",
    "title": "A night in November"
  },
  {
    "authors": [
      {
        "revision": 1,
        "type": "author",
        "key": "OL2802829A",
        "name": "Lorna Read",
        "last_modified": "2008-04-29 15:03:11.581851"
      }
    ],
    "publishers": [
      "Collins"
    ],
    "number_of_pages": 96,
    "publish_date": "November 3, 1997",
    "latest_revision": 5,
    "last_modified": "2022-12-17T03:01:10.857196",
    "title": "The Sleepover Girls Go Spice.... (The Sleepover Club)",
    "revision": 5,
    "key": "OL9921201M",
    "subjects": [
      "Fiction"
    ],
    "type": "edition"
  }
]

=== fmarkulin/fer-or/export.json
[
  {
    "last_modified": "2022-11-15T20:13:03.789779",
    "key": "OL10551435M",
    "type": "edition",
    "number_of_pages": 127,
    "latest_revision": 13,
    "authors": [
      {
        "last_modified": "2008-08-19 18:21:52.259027",
        "type": "author",
        "revision": 2,
        "key": "OL1158982A",
        "name": "Norman T. Carrington"
      }
    ],
    "subjects": [
      "English literature: literary criticism",
      "Novels, other prose & writers: 19th century",
      "Designed / suitable for A & AS Level",
      "For National Curriculum Key Stage 4 & GCSE",
      "Study guides, home study & revision notes",
      "English",
      "Children: Young Adult (Gr. 7-9)"
    ],
    "revision": 13,
    "publishers": [
      "Palgrave Macmillan"
    ],
    "publish_date": "August 7, 1992",
    "title": "Brodie's Notes on Emily Bronte's \"Wuthering Heights\" (Brodies Notes)"
  },
  {
    "number_of_pages": 78,
    "authors": [
      {
        "revision": 1,
        "name": "A. B Kneisel",
        "key": "OL4473583A",
        "last_modified": "2008-09-02 18:39:32.675717",
        "type": "author"
      }
    ],
    "type": "edition",
    "latest_revision": 3,
    "revision": 3,
    "subjects": [
      "Aristophanes"
    ],
    "title": "Aristophanes, ein Spiegel unserer Zeit.",
    "publishers": [
      "P. Schettlers"
    ],
    "key": "OL13994901M",
    "publish_date": "1913",
    "last_modified": "2010-04-13T09:56:10.635564"
  },
  {
    "key": "OL1413776M",
    "publish_date": "1993",
    "last_modified": "2022-12-05T06:01:35.024861",
    "subjects": [
      "World War, 1939-1945 -- Campaigns -- Europe.",
      "World War, 1939-1945 -- Campaigns -- Europe -- Pictorial works."
    ],
    "title": "War in Europe",
    "authors": [
      {
        "type": "author",
        "revision": 2,
        "last_modified": "2008-08-30 03:01:23.375753",
        "key": "OL581008A",
        "name": "Sidney C. Moody"
      }
    ],
    "publishers": [
      "Presidio"
    ],
    "revision": 10,
    "type": "edition",
    "number_of_pages": 192,
    "latest_revision": 10
  },
  {
    "type": "edition",
    "authors": [
      {
        "revision": 1,
        "last_modified": "2008-09-28 21:35:54.283711",
        "key": "OL5295787A",
        "type": "author",
        "name": "W. E. Hamilton"
      }
    ],
    "latest_revision": 5,
    "title": "Muskoka sketch",
    "subjects": [
      "Muskoka (Ont. : District) -- Description and travel.",
      "Muskoka (Ont. : District) -- History."
    ],
    "key": "OL21357082M",
    "revision": 5,
    "last_modified": "2012-08-08T21:10:59.924864",
    "publish_date": "1983",
    "publishers": [
      "Times Printing Company"
    ],
    "number_of_pages": 26
  },
  {
    "revision": 3,
    "latest_revision": 3,
    "key": "OL22885087M",
    "number_of_pages": 200,
    "subjects": [
      "Methodists -- Ireland."
    ],
    "publish_date": "1803",
    "type": "edition",
    "publishers": [
      "Printed by H. Colbert"
    ],
    "title": "A Letter to Alexander Knox, Esq. M.R.I.A.",
    "last_modified": "2012-08-07T10:18:24.946860",
    "authors": [
      {
        "name": "Walker, John",
        "last_modified": "2012-06-07T08:18:43.478466",
        "key": "OL2555401A",
        "type": "author",
        "revision": 2
      }
    ]
  },
  {
    "latest_revision": 2,
    "revision": 2,
    "authors": [
      {
        "name": "L. N. Carrier",
        "type": "author",
        "last_modified": "2008-09-28 19:19:44.680177",
        "key": "OL5288239A",
        "revision": 1
      }
    ],
    "publish_date": "1880",
    "key": "OL25465456M",
    "title": "Les Institutions de credit-foncier. Quelques notes sur leur but, leur organisation et leur origine",
    "publishers": [
      "L.J. Demers"
    ],
    "number_of_pages": 48,
    "last_modified": "2020-05-21T10:17:30.189173",
    "type": "edition",
    "subjects": [
      "Credit",
      "Banks and banking"
    ]
  },
  {
    "publishers": [
      "Biblica, Publications de Saint André"
    ],
    "number_of_pages": 298,
    "subjects": [
      "Criticism, interpretation",
      "Bible"
    ],
    "revision": 3,
    "publish_date": "1965",
    "authors": [
      {
        "last_modified": "2008-04-01 03:28:50.625462",
        "type": "author",
        "revision": 1,
        "key": "OL2153880A",
        "name": "Rose, A."
      }
    ],
    "last_modified": "2020-05-15T03:58:15.877548",
    "key": "OL26545029M",
    "latest_revision": 3,
    "title": "Psaumes et prière chrétienne",
    "type": "edition"
  },
  {
    "publishers": [
      "IDG Books Worldwide"
    ],
    "last_modified": "2020-11-20T15:58:35.964496",
    "publish_date": "1995",
    "subjects": [
      "Home video systems.",
      "Video tape recorders.",
      "Camcorders.",
      "Television -- Equipment and supplies."
    ],
    "type": "edition",
    "authors": [
      {
        "last_modified": "2008-09-12 15:59:54.226722",
        "revision": 2,
        "name": "Gordon McComb",
        "type": "author",
        "key": "OL51749A"
      }
    ],
    "number_of_pages": 331,
    "latest_revision": 10,
    "revision": 10,
    "title": "VCRs & camcorders for dummies",
    "key": "OL824543M"
  },
  {
    "type": "edition",
    "revision": 6,
    "number_of_pages": 48,
    "title": "A night in November",
    "latest_revision": 6,
    "last_modified": "2020-11-21T08:24:06.596410",
    "publish_date": "1995",
    "publishers": [
      "New Island Books",
      "Nick Hern Books"
    ],
    "authors": [
      {
        "last_modified": "2008-08-31 21:11:02.340397",
        "key": "OL500580A",
        "name": "Marie Jones",
        "type": "author",
        "revision": 2
      }
    ],
    "subjects": [
      "Protestants -- Northern Ireland -- Belfast -- Drama.",
      "Soccer -- Northern Ireland -- Belfast -- Drama."
    ],
    "key": "OL904472M"
  },
  {
    "title": "The Sleepover Girls Go Spice.... (The Sleepover Club)",
    "number_of_pages": 96,
    "authors": [
      {
        "revision": 1,
        "key": "OL2802829A",
        "name": "Lorna Read",
        "last_modified": "2008-04-29 15:03:11.581851",
        "type": "author"
      }
    ],
    "key": "OL9921201M",
    "last_modified": "2022-12-17T03:01:10.857196",
    "subjects": [
      "Fiction"
    ],
    "revision": 5,
    "publish_date": "November 3, 1997",
    "latest_revision": 5,
    "type": "edition",
    "publishers": [
      "Collins"
    ]
  }
]
